
service:
  aws:
    access:
      key: ${AWS_ACCESS_KEY}
      secret: ${AWS_ACCESS_SECRET}
    s3:
      bucket:
        region: us-east-2
        photo: spring-aws-upload

spring:
  application:
    name: aws-s3-upload
  datasource:
      url: jdbc:mysql://localhost:3308/user-aws-profile
      username: user
      password: pwd
      initialization-mode: always
  # Strongly recommend to set this property to "none" in a production environment!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


